### ISSUE TITLE
Breaking Issue with 0.5.x?

### ISSUE THREAD

**Issue by cooganb** [ericxtang/browser-solc#4]
Hi there! Been using this for an in-browser Solidity browser and but can't seem to migrate to Solidity 0.5.x. It seems to be related to this issue of `import` and `export` JSON for 0.5.x:

https://ethereum.stackexchange.com/questions/63267/solc-compile-0-5-0-is-not-working-like-0-4-version

Love being able to use `browser-solc` as it avoids `import` and would love to continue! Let me know what more details I can provide.

**Comment by maxwellfoley3** [comment]
I had the same issue. The problem is simply that @ericxtang hasn't updated this repo since version 0.5 came out. If you go into `package.json` and specify version 0.5 of solc-js, and then rebuild `index.js` yourself using the command in the readme, it should work (although solc itself has changed the syntax around using it so you will have to change your code as well)

**Comment by cooganb** [comment]
@maxwellfoley3 Thank you for this! I'm having some trouble rebuilding it after specifying the new version. After running `npm install` then `npm run build`, I get:

`Error: Cannot find module 'solc/wrapper' from '/Users/coogan/github/browser-solc/src'`

Any ideas of how to get around this?? Super appreciate it.

**Comment by cooganb** [comment]
okay, I think that was just an install issue and think I've gotten past it. however, now I'm having issues with the adjusted file input format for 0.5.x compiler related to this SO question:

https://ethereum.stackexchange.com/questions/63267/solc-compile-0-5-0-is-not-working-like-0-4-version

@maxwellfoley3 , were you able to get your input corrected?

**Comment by Tectract** [comment]
Hi coogan. Did you ever get compile working with the newest version of solc, 0.5.x+?

I'm getting this error:

RuntimeError: abort(Assertion failed: Cannot call unknown function compileJSON, make sure it is exported). Build with -s ASSERTIONS=1 for more info.

m browser-solc.min.js:7245

**Comment by Tectract** [comment]
Fixed in my fork. See PR https://github.com/ericxtang/browser-solc/pull/5

I changed "compileJSON" to "solidity_compile" in one place, to accomodate the newest solcjson code compilation standards. I added a little notes. Thank you, I am your code angel~

**Comment by cooganb** [comment]
You are indeed my code angel! Gracias.

Any other code needed to run this?

**Comment by Tectract** [comment]
you'll need to wrap your solidity code text, as you mentioned in that SA thread. I put those notes in [my repo](https://github.com/Tectract/browser-solc) and in [the PR](https://github.com/ericxtang/browser-solc/pull/5).

You'll need to update your parsing routine as the result JSON from the compiler has changed format a little, but you can figure that out.

So now, we need to figure out how to make it work under Chrome, and then Brave, lol. 

See this [Ethereum / Chrome ticket](https://github.com/ethereum/remix-ide/issues/2794)

and this [Ethereum / Solc-JS ticket](https://github.com/ethereum/solc-js/issues/226)

and this [Metamask Brave ticket](https://github.com/MetaMask/metamask-extension/issues/5446)

**Comment by H4wk-eye** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
robmuth, @ArjunBhuptani, @francishero, @ligurio, @beevelop, @Masquerade0097, @jeluard, @futuregraph, @ya-nsh, @puneetjindal, @mathewdgardner, @pradyuman-verma, @kalex96, @mattmanuel90, @rahul8590, @patrickhayesweb, @AllanM007, @nmorgens, @ztephenc, @YuKarabu
